const CreateAwardUseCase = require('../use-cases/CreateAwardUseCase');
const AwardRepository = require('../../repositories/AwardRepository');
const QuotationRepository = require('../../../procurement/repositories/QuotationRepository');
const UnitOfWork = require('../../../../shared/application/UnitOfWork');
const TransactionManager = require('../../../../shared/application/TransactionManager');
const OutboxRepository = require('../../../../shared/infrastructure/outbox/OutboxRepository');
const PolicyExecutionMiddleware = require('../../../../shared/application/PolicyExecutionMiddleware');

class AwardCreationPolicy {
  /**
   * Consumes QuotationAcceptedEvent and attempts to create an Award.
   * Adheres to ADR-008: Process Manager Boundaries (Restart-Safe & Query-First Idempotency).
   */
  static get handle() {
    return PolicyExecutionMiddleware.wrap('AwardCreationPolicy', async (event, t) => {
      const { quotationId, buyerOrganizationId } = event.payload;

      // Prepare dependencies (In a real app, inject via DI container)
      const awardRepo = new AwardRepository();
      const quotationRepo = new QuotationRepository();
      const transactionManager = new TransactionManager();
      const outboxRepo = new OutboxRepository();
      const uow = new UnitOfWork({ transactionManager, outboxRepo });

      const createAwardUseCase = new CreateAwardUseCase({
        awardRepo,
        quotationRepo,
        uow
      });

      console.log(`[AwardCreationPolicy] Triggering CreateAwardUseCase for Quotation ${quotationId}...`);
      await createAwardUseCase.execute({
        quotationId: quotationId,
        buyerOrganizationId: buyerOrganizationId,
        actorId: 'SYSTEM',
        notes: 'Auto-generated by AwardCreationPolicy',
        correlationId: event.correlationId,
        causationId: event.eventId // The cause of the new events is this event
      }, t);
    });
  }
}

module.exports = AwardCreationPolicy;
