const AwardCreationPolicy = require('../src/modules/sales/application/policies/AwardCreationPolicy');
const CreateAwardUseCase = require('../src/modules/sales/application/use-cases/CreateAwardUseCase');
const { Award: AwardModel } = require('../sequelize_setup');
const EventBus = require('../src/shared/infrastructure/eventBus/EventBus');
const PolicyRegistry = require('../src/shared/infrastructure/eventBus/PolicyRegistry');

// Mock Dependencies
jest.mock('../src/modules/sales/application/use-cases/CreateAwardUseCase');
jest.mock('../sequelize_setup', () => {
  return {
    Award: {
      findOne: jest.fn(),
    }
  };
});
jest.mock('../src/shared/infrastructure/eventBus/EventBus', () => ({
  subscribe: jest.fn(),
  publish: jest.fn(),
}));

describe('SPECIFICATION: AwardCreationPolicy (Process Manager)', () => {
  let mockEvent;

  beforeEach(() => {
    jest.clearAllMocks();

    mockEvent = {
      name: 'QuotationAcceptedEvent',
      payload: {
        quotationId: 'q-123',
        purchaseRequestId: 'pr-456',
        sellerOrganizationId: 'org-789',
        status: 'accepted'
      }
    };
  });

  it('1. PM-03: Should trigger CreateAwardUseCase when receiving QuotationAcceptedEvent', async () => {
    AwardModel.findOne.mockResolvedValue(null); // No existing award

    const executeSpy = jest.fn().mockResolvedValue();
    CreateAwardUseCase.prototype.execute = executeSpy;

    await AwardCreationPolicy.handle(mockEvent);

    // Verify Query First was executed
    expect(AwardModel.findOne).toHaveBeenCalledWith({ where: { quotationId: 'q-123' } });

    // Verify UseCase was executed with correct arguments
    expect(executeSpy).toHaveBeenCalledWith({
      quotationId: 'q-123',
      actorId: 'SYSTEM',
      notes: 'Auto-generated by AwardCreationPolicy'
    });
  });

  it('2. PM-04: Should be Idempotent (Ignore event if Award already exists - Query First)', async () => {
    AwardModel.findOne.mockResolvedValue({ id: 'existing-award-id' }); // Award exists

    const executeSpy = jest.fn();
    CreateAwardUseCase.prototype.execute = executeSpy;

    await AwardCreationPolicy.handle(mockEvent);

    // Verify Query First was executed
    expect(AwardModel.findOne).toHaveBeenCalledWith({ where: { quotationId: 'q-123' } });

    // UseCase must NOT be executed
    expect(executeSpy).not.toHaveBeenCalled();
  });

  it('3. PM-04/PM-05: Should handle Race Condition gracefully (UniqueConstraintError)', async () => {
    AwardModel.findOne.mockResolvedValue(null); // Query says no award exists

    // But DB throws unique constraint on creation (another worker got there first)
    const uniqueError = new Error("Validation error");
    uniqueError.name = 'SequelizeUniqueConstraintError';

    const executeSpy = jest.fn().mockRejectedValue(uniqueError);
    CreateAwardUseCase.prototype.execute = executeSpy;

    // Should not throw!
    await expect(AwardCreationPolicy.handle(mockEvent)).resolves.not.toThrow();
  });

  it('4. PM-06: Failure Isolation (Should throw normal errors to EventBus)', async () => {
    AwardModel.findOne.mockResolvedValue(null);

    const normalError = new Error("Database connection failed");
    const executeSpy = jest.fn().mockRejectedValue(normalError);
    CreateAwardUseCase.prototype.execute = executeSpy;

    // Should throw! EventBus or DLQ will handle the retry
    await expect(AwardCreationPolicy.handle(mockEvent)).rejects.toThrow("Database connection failed");
  });

  it('5. EventBus Registration: Should be registered in PolicyRegistry', () => {
    PolicyRegistry.registerAll();
    
    // Verify EventBus.subscribe was called with the correct event and handler
    expect(EventBus.subscribe).toHaveBeenCalledWith(
      "QuotationAcceptedEvent",
      expect.any(Function)
    );
  });
});
